#CREATE TABLE for raw data to be loaded into
CREATE TABLE Boston_merge_clean (
ID INT PRIMARY KEY, 
name VARCHAR,
summary VARCHAR,
host_id int,
transit VARCHAR,
access VARCHAR,
house_rules VARCHAR,
host_name VARCHAR,
host_since VARCHAR,
host_response_rate VARCHAR,
thumbnail_url VARCHAR,
street VARCHAR,
neighbourhood VARCHAR,
property_type VARCHAR,
room_type VARCHAR,
city VARCHAR,
state VARCHAR,
price VARCHAR,
accommodates int,
bathrooms float,
bedrooms float,
beds float,
amenities VARCHAR,
square_feet float,
security_deposit VARCHAR,
cleaning_fee VARCHAR,
minimum_nights int,
first_review VARCHAR,
last_review VARCHAR,
review_scores_rating float,
review_scores_accuracy float,
review_scores_cleanliness float,
review_scores_checkin float,
review_scores_communication float,
review_scores_location float,
review_scores_value float,
cancellation_policy VARCHAR,
reviews_per_month float,
reviewer_id int,
comments VARCHAR
);

#CREATE TABLE for raw data to be loaded into
CREATE TABLE Seattle_merge_clean (
ID INT PRIMARY KEY, 
name VARCHAR,
summary VARCHAR,
host_id int,
transit VARCHAR,
host_name VARCHAR,
host_since VARCHAR,
host_response_rate VARCHAR,
thumbnail_url VARCHAR,
street VARCHAR,
neighbourhood VARCHAR,
property_type VARCHAR,
room_type VARCHAR,
city VARCHAR,
state VARCHAR,
price VARCHAR,
accommodates int,
bathrooms float,
bedrooms float,
beds float,
amenities VARCHAR,
square_feet float,
security_deposit VARCHAR,
cleaning_fee VARCHAR,
minimum_nights int,
first_review VARCHAR,
last_review VARCHAR,
review_scores_rating float,
review_scores_accuracy float,
review_scores_cleanliness float,
review_scores_checkin float,
review_scores_communication float,
review_scores_location float,
review_scores_value float,
cancellation_policy VARCHAR,
reviews_per_month float,
reviewer_id int,
comments VARCHAR
);
